name: Publish container images

on:
  push:
    branches: ['main']

env:
  alpine_version: 3.16.2
  thttpd_version: 2.29

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: latest ${{ env.thttpd_version }}
          dockerfiles: Containerfile
          build-args: |
            alpine_version=${{ env.alpine_version }}
            thttpd_version=${{ env.thttpd_version }}
      
      - name: Push to ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}

